### PR TITLE
Move opt-ins for experimental annotation to build.gradle file

### PR DESCRIPTION
**Pull request by luizgrp**
#### WHAT

Move opt-ins for experimental annotation to build.gradle file

#### WHY

https://github.com/google/horologist/pull/1123#discussion_r1143312738

#### Checklist :clipboard:
- [N/A] Add explicit visibility modifier and explicit return types for public declarations
- [x] Run spotless check
- [x] Run tests
- [N/A] Update metalava's signature text files

### CODE REVIEW

**Review by yschimke — APPROVED** [review]
This seems nicer to me, Filip should have a say as well.

What is our rule after this?
- horologist annotations in gradle
- other experimental annotations in build.gradle.kts? Source files?

**Comment by luizgrp** [comment]
As far as I understand, the other ones can't just be in build.gradle, as the project is used with another build system. It only works with the horologist annotation because they are removed before importing.

**Comment by yschimke** [comment]
@luizgrp so should we move them all into code? Not necessary in this PR, just curious what the exact rules are when adding more.

**Comment by yschimke** [comment]
@luizgrp are we intending to land this, do you want it in the next release?  Just noticed the conflicts.

**Comment by luizgrp** [comment]
yes, intend to land, not necessary in next release

waiting on review from @fstanis as per your request, not going to sort conflicts until then

**Pull request merged**
