### PR TITLE
API 26 for tiles

### PR DESCRIPTION
**Pull request by yschimke**
Fixes a build issue with tiles, which depends on 26.

### CODE REVIEW

**Comment by shumelchyk** [comment]
So at the end Tiles require `minSDK=26`?

**Review by shumelchyk — APPROVED** [review]

**Comment by yschimke** [comment]
> So at the end Tiles require `minSDK=26`?

I believe so https://github.com/android/wear-os-samples/blob/main/WearTilesKotlin/app/build.gradle#L27

**Comment by fstanis** [comment]
This used to be the case, but now tiles is min 25: https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:wear/tiles/tiles/build.gradle;l=45

**Comment by yschimke** [comment]
tiles-testing is the issue.  https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:wear/tiles/tiles-testing/build.gradle

**Pull request merged**
