### PR TITLE
Prepare compose modules to be converted to Kotlin DSL

### PR DESCRIPTION
**Pull request by oas004**
#### WHAT
Preparing the compose modules to be converted to Kotlin DSL

#### WHY
Following up #846  relating to #833 

#### HOW
Following https://docs.gradle.org/current/userguide/migrating_from_groovy_to_kotlin_dsl.html#prepare_your_groovy_scripts to make the modules easy to convert to Kotlin DSL

#### Checklist :clipboard:
- [x] Add explicit visibility modifier and explicit return types for public declarations
- [x] Run spotless check
- [x] Run tests
- [x] Update metalava's signature text files

### CODE REVIEW

**Comment by oas004** [comment]
Rebase with main ☝️

**Comment by oas004** [comment]
Is CI cancelled after 30 min? :)

**Review by luizgrp — APPROVED** [review]
LGTM

**Comment by luizgrp** [comment]
> Is CI cancelled after 30 min? :)

[yup](https://github.com/google/horologist/blob/4848bf8ac38c8ae289a265f697fed7912d1e31ab/.github/workflows/build.yml#L19), we might have to review this, it seems to be cancelling more frequently

**Comment by oas004** [comment]
Aha okay, well good to know  :) Thanks! :)

**Pull request merged**
