### PR TITLE
Use Material Chip for the secondary placeholder chip

### LINKED ISSUE #332: Change implementation of SecondaryPlaceholderChip to use Chip
#### WHAT

Change implementation of [SecondaryPlaceholderChip](https://github.com/google/horologist/blob/c0fed820b2d7154a22104e54f52d19c5aefecda8/media-ui/src/main/java/com/google/android/horologist/media/ui/components/base/SecondaryPlaceholderChip.kt) to use [Chip](https://github.com/androidx/androidx/blob/5775cb72bdc32a90328bf39e212fab31c5960316/wear/compose/compose-material/src/commonMain/kotlin/androidx/wear/compose/material/Chip.kt#L282) instead of building everything from scratch, and pass the grey shapes as params to `label`, `secondaryLabel`, and `icon`.

PS: remember to remove this [dependency](https://github.com/google/horologist/blob/c0fed820b2d7154a22104e54f52d19c5aefecda8/media-ui/build.gradle#L107) from the module when done.

#### WHY

https://github.com/google/horologist/pull/328#discussion_r914674450

#### Expected outcome from this task

- Implementation of `SecondaryPlaceholderChip` is changed to use `Chip`;
- Preview for `SecondaryPlaceholderChip` is not affected;
- Snapshot test for `SecondaryPlaceholderChip` is not affected;

### PR DESCRIPTION
**Pull request by oas004**
First of all, thank you so much for this cool library! I really like it! 😃 🤩 

#### WHAT
In this PR I have started to use the material chip apis for the secondary placeholder chip instead of making it from basic composable as it was before 😃 

#### WHY
fixes #332 

#### HOW
I have changed the implementation and seen that the screenshot test that was used on the old implementation still passes.

Screenshot 2022-08-22 at 15 16 07

#### Checklist :clipboard:
- [x] Add explicit visibility modifier and explicit return types for public declarations
- [x] Run spotless check
- [x] Run tests
- [x] Update metalava's signature text files

### CODE REVIEW

**Comment by oas004** [comment]
I don't quite understand why this test now fails. Locally, the test passes with 0.1% difference, but on CI it fails with the same amount of difference 🤔 The test also states that 0.1% difference is max

**Comment by yschimke** [comment]
The diff seems to show a real issue

image

This is with the Android Studio "Image Diff" plugin https://plugins.jetbrains.com/plugin/12691-image-diff

**Comment by oas004** [comment]
> The diff seems to show a real issue
> 
> image
> 
> This is with the Android Studio "Image Diff" plugin https://plugins.jetbrains.com/plugin/12691-image-diff

Oo thanks! Have to use that plugin! Converting to draft until I get it perfect 😄

**Review by luizgrp — APPROVED** [review]
LGTM - thanks for fixing this! 👍

**Pull request merged**
