### PR TITLE
Fix responsive message padding

### PR DESCRIPTION
**Pull request by yschimke**
#### WHAT

Fix responsive message padding

#### WHY

Too cramped

#### Checklist :clipboard:
- [ ] Add explicit visibility modifier and explicit return types for public declarations
- [ ] Run spotless check
- [ ] Run tests
- [ ] Update metalava's signature text files

### CODE REVIEW

**Comment by yschimke** [comment]
fixing screenshots in the background

**Comment by yschimke** [comment]
I suspect this is not 100% correct. There is already padding.

```
                        Row(
                            Modifier
                                .fillMaxWidth()
                                .padding(
                                    top = if (content != null || message != null) 12.dp else 0.dp,
                                ),
```

**Review by BowerSteve — COMMENTED** [review]
Also remove '|| message != null' from line 149?

**Review by BowerSteve — APPROVED** [review]
LGTM

**Pull request merged**
