### PR TITLE
Add support and a test for image transparency

### PR DESCRIPTION
**Pull request by yschimke**
#### WHAT

Support format for tile image conversions to support transparency.

#### WHY

Fixing https://github.com/google/horologist/issues/251

#### Checklist :clipboard:
- [ ] Add explicit visibility modifier and explicit return types for public declarations
- [ ] Run spotless check
- [ ] Run tests
- [ ] Update metalava's signature text files

### CODE REVIEW

**Comment by Tolriq** [comment]
After a short night of sleep, I think it's simpler and better to drop the bitmap conversion and leave it to the user with doc explaining it. Most conversion up or down should be done with dithering and specific options to ensure better result depending on the kind of image anyway.

That function should get the bitmap config and simply have a mapping for the ImageFormat from the bitmap.

**Comment by yschimke** [comment]
OK, I'll land this.  Agreed, I was struggling for how the library can know what the right thing to do is.

**Comment by yschimke** [comment]
@Tolriq care to give me a LGTM?

**Comment by Tolriq** [comment]
@yschimke what I mean is that `toImageResource` should be parameter less and not do any conversion at all.

It should just convert the bitmap.config to an Imageformat to pass down and have proper javadoc about it.

**Comment by yschimke** [comment]
It needs to fail if your Bitmap has the wrong format then.  I don't see how that helps.

I can document that you should ensure it's right before calling, but that seems like a sharp edge.

**Comment by yschimke** [comment]
OK, I see what you mean.  Yep, that is a better idea.

**Comment by Tolriq** [comment]
> It needs to fail if your Bitmap has the wrong format then. I don't see how that helps.

This makes things explicit, automatic bitmap modifications makes it hard for the dev to figure out what is happening when there is an issue.
I took me a lot of time to search on that function and not on the bitmap generation itself why cropping was not working.

Worse is that it could work with artifact not seen on the test images and being ugly when in prod and actual user images.

**Pull request merged**
