### PR TITLE
Make KnownDuration a data class

### PR DESCRIPTION
**Pull request by yschimke**
#### WHAT

Make KnownDuration a data class

#### WHY

Want equality for StateFlow updates.

#### Checklist :clipboard:
- [ ] Add explicit visibility modifier and explicit return types for public declarations
- [ ] Run spotless check
- [ ] Run tests
- [ ] Update metalava's signature text files

### CODE REVIEW

**Review by luizgrp — APPROVED** [review]
there was a reason it wasn't added as data class, maybe it only made sense in the previous media toolkit project, can't remember now

**Comment by yschimke** [comment]
That sounds familiar, but without this the position keeps changing evey second even when paused.

**Comment by luizgrp** [comment]
for future reference: https://github.com/google/horologist/blob/bdb1f95100c1aa6ac747674fc397072e24efa074/media-data/src/test/java/com/google/android/horologist/media/data/repository/PlayerRepositoryImplTest.kt#L948

**Comment by yschimke** [comment]
data classes can be bad for public APIs, but if I was holding a hard line about that, I think I've softened now.

https://jakewharton.com/public-api-challenges-in-kotlin/

**Comment by yschimke** [comment]
Let's revert if we remember a reason we still hold.

**Pull request merged**
