### PR TITLE
UI Playback fix

### PR DESCRIPTION
**Pull request by yschimke**
#### WHAT

Clicking an item wasn't working, so carry through the id into the UI.

Also ensures the TimeText scrolls out of the way.

#### WHY

UI Fixes for testing.

#### Checklist :clipboard:
- [ ] Add explicit visibility modifier and explicit return types for public declarations
- [ ] Run spotless check
- [ ] Run tests
- [ ] Update metalava's signature text files

### CODE REVIEW

**Comment by luizgrp** [comment]
any possibility of putting this on hold until work going in https://github.com/google/horologist/pull/369 is merged?

**Comment by yschimke** [comment]
Sure!

**Comment by luizgrp** [comment]
https://github.com/google/horologist/pull/369 has been merged and you can proceed with this PR, thanks for your patience!

**Review by luizgrp — APPROVED** [review]

**Comment by yschimke** [comment]
Waiting on https://github.com/google/horologist/pull/376/files#diff-b2dc30c1b5bc23c367202d76f3bf7ec5aed492b8320acedac0f53aede950de05

**Comment by luizgrp** [comment]
ok seeing the diff after you updated the pr, it looks like #376 makes the changes of this PR redundant

**Comment by yschimke** [comment]
Thanks, even better. I updated main, thinking this landed and didn't see it. And then didn't twig after seeing this.

**Pull request closed without merging**
