### PR TITLE
Catch exceptions requesting network

### PR DESCRIPTION
**Pull request by yschimke**
#### WHAT

Catch exceptions requesting a high bandwidth network

#### WHY

fixes https://github.com/google/horologist/issues/2417

#### Checklist :clipboard:
- [ ] Add explicit visibility modifier and explicit return types for public declarations
- [ ] Run spotless check
- [ ] Run tests
- [ ] Update metalava's signature text files

### CODE REVIEW

**Comment by yschimke** [comment]
cc @Tolriq

**Comment by Tolriq** [comment]
Thanks.

Does it make sense to only catch that specific known error? Usually Google does not like large catch all.

**Comment by yschimke** [comment]
@Tolriq I can't catch on the type. I can rethrow if the class name doesn't match.

Thoughts?

**Comment by Tolriq** [comment]
It was more a conceptual best practices question, I have no issue on my side for a catch all.

**Review by Tolriq — APPROVED** [review]

**Comment by yschimke** [comment]
@Tolriq Do you need this in 0.6.x or 0.7.x-alpha?

**Pull request merged**
