### PR TITLE
A different approach to the ActiveDurationText

### PR DESCRIPTION
**Pull request by yschimke**
#### WHAT

A different approach to the ActiveDurationText

#### WHY

Introduce a slot API, and use repeatOnLifecycle

#### Checklist :clipboard:
- [x] Add explicit visibility modifier and explicit return types for public declarations
- [x] Run spotless check
- [x] Run tests
- [x] Update metalava's signature text files

### CODE REVIEW

**Comment by yschimke** [comment]
@garanj Thinking more about the lifecycle code.

We could remove that and turn the ActiveDurationCheckpoint into a Flow, that ticks every X.  IT should probably live in a ViewModel and the UI is just subscribed to it, while the UI is open.

Or we could take the approach from Media and turn the exercise state into some UI State, with a predictor function.

**Review by garanj — COMMENTED** [review]
Awesome!

**Comment by garanj** [comment]
> @garanj Thinking more about the lifecycle code.
> 
> We could remove that and turn the ActiveDurationCheckpoint into a Flow, that ticks every X. IT should probably live in a ViewModel and the UI is just subscribed to it, while the UI is open.
> 
> Or we could take the approach from Media and turn the exercise state into some UI State, with a predictor function.
> 
> Overkill for now, just discussion.

I had wondered about a flow and putting it in the ViewModel. Makes sense, I wondered if there might ever be a case where the app wouldn't be using a ViewModel?

**Comment by yschimke** [comment]
> I wondered if there might ever be a case where the app wouldn't be using a ViewModel?

It's not exclusive. And the same patterns work if not, but in our MAD guidelines the ViewModel is a useful place to hoist state to.

**Pull request merged**
