### PR TITLE
Fix volume screen images.

### PR DESCRIPTION
**Pull request by yschimke**
#### WHAT

CI tests are failing because of a different result for volume tests.  Try recreating the images.

#### WHY

Went from 1000px to 999 for some reason?

#### Checklist :clipboard:
- [x] Add explicit visibility modifier and explicit return types for public declarations
- [x] Run spotless check
- [x] Run tests
- [x] Update metalava's signature text files

### CODE REVIEW

**Review by luizgrp — APPROVED** [review]
weird!

**Comment by yschimke** [comment]
@luizgrp Going to raise a paparazzi bug, this is weird

**Comment by yschimke** [comment]
Actually it could be my code WearSnapHandler, so need to check that first.

**Comment by luizgrp** [comment]
loads of weirds things going on with these paparazzi tests, main branch is green after merging this but my PRs that are up to date with main are failing with:

```
com.google.android.horologist.audio.ui.VolumeScreenIndividualTest > volumeScreenAtMaximum FAILED
    java.lang.NullPointerException at VolumeScreenIndividualTest.kt:66
com.google.android.horologist.audio.ui.VolumeScreenIndividualTest > volumeScreenAtMinimum FAILED
    java.lang.NullPointerException at VolumeScreenIndividualTest.kt:49
com.google.android.horologist.audio.ui.VolumeScreenIndividualTest > volumeScreenWithLongTest FAILED
    java.lang.NullPointerException at VolumeScreenIndividualTest.kt:83
```

**Pull request merged**
