### PR TITLE
[Install App prompt] Improve UI according to redlines

### PR DESCRIPTION
**Pull request by luizgrp**
#### WHAT

Improve UI according to redlines.

Normal screen

https://github.com/google/horologist/assets/878134/adba89da-b98e-4127-a2d8-d696ae41303a

Small screen

https://github.com/google/horologist/assets/878134/d00b6d50-62b5-4e7c-a412-0ae3fae7c88b

#### Checklist :clipboard:
- [N/A] Add explicit visibility modifier and explicit return types for public declarations
- [x] Run spotless check
- [x] Run tests
- [N/A] Update metalava's signature text files

### CODE REVIEW

**Comment by yschimke** [comment]
What is the little jump on the normal screen video just after it opens?

**Comment by luizgrp** [comment]
> What is the little jump on the normal screen video just after it opens?

I tried to expand it, it won't expand as there is no further content.

**Review by yschimke — APPROVED** [review]
LGTM - but not sure if you are waiting for Chiara or Garan.

**Comment by luizgrp** [comment]
cc: @mlangsman

**Pull request merged**
