### PR TITLE
Rename resourceResult to resourceState in Renderer

### LINKED ISSUE #504: Naming inconsistency between TileLayoutPreview and TileRenderer
`TileLayoutPreview` has a parameter called `resourceState`

`TileRenderer` (and subclasses) call this `resourceResults`. 

I think `resourceState` works a lot better.

### PR DESCRIPTION
**Pull request by oas004**
#### WHAT
In this PR I have renamed resourceResult to resourceState in the BaseRender classes and everywhere it is inherited.

#### WHY
fixes #504

#### HOW
Using the refactor tools provided by Android Studio.

#### Checklist :clipboard:
- [x] Run spotless check
- [x] Run tests
- [ ] Update metalava's signature text files

### CODE REVIEW

**Comment by oas004** [comment]
I guess since this is a breaking change in the API, I would need to update `metalava` signature. I tried to run `./gradlew metalavaGenerateSignature` is that enough? :) 

Furthermore, I was thinking as this API is marked with `@ExperimentalHorologistTilesApi` is it okay to just change the API? Or do I need to deprecate this and make a wrapper? :)

**Comment by yschimke** [comment]
The contributing guide has our commands to fix APIs https://github.com/google/horologist/blob/main/CONTRIBUTING.md

```
/home/runner/work/horologist/horologist/media-ui/build/metalava/current.txt:837: error: Attempted to change parameter name from resourceResults to resourceState in method com.google.android.horologist.media.ui.tiles.MediaCollectionsTileRenderer.produceRequestedResources [ParameterNameChange]
Aborting: Found compatibility problems checking the public API (/home/runner/work/horologist/horologist/media-ui/build/metalava/current.txt) against the API in /home/runner/work/horologist/horologist/media-ui/api/current.api
> Task :media-ui:metalavaCheckCompatibilityRelease FAILED
```

**Comment by yschimke** [comment]
Since https://github.com/google/horologist/pull/483/files

I think it's now two different tasks.  Try `./gradlew metalavaGenerateSignatureDebug`

**Comment by oas004** [comment]
> Since https://github.com/google/horologist/pull/483/files
> 
> I think it's now two different tasks. Try `./gradlew metalavaGenerateSignatureDebug`



> Since https://github.com/google/horologist/pull/483/files
> 
> I think it's now two different tasks. Try `./gradlew metalavaGenerateSignatureDebug`

I think that worked! Thanks! :)

**Review by yschimke — APPROVED** [review]

**Comment by yschimke** [comment]
I think the test failure is unrelated and I'll look into it.

**Comment by yschimke** [comment]
I'm updating the branch and trying again.

**Pull request merged**
