### PR TITLE
Testing mirror

### PR DESCRIPTION
**Pull request by yschimke**
#### WHAT
| Direction | Left    | Right    |
| :---:   | :---: | :---: |
|  | AutoMirror   | AutoMirror + rtlMode=Mirrored   |
| RTL | AutoMirror   | AutoMirror + rtlMode=Mirrored   |
|  | Filled   | AutoMirror   |
| RTL | Filled   | AutoMirror   |

image

#### Checklist :clipboard:
- [ ] Add explicit visibility modifier and explicit return types for public declarations
- [ ] Run spotless check
- [ ] Run tests
- [ ] Update metalava's signature text files

### CODE REVIEW

**Comment by yschimke** [comment]
@luizgrp I suspect we should consider whether we need rtlMode any more.  Or use it only in extreme cases?

**Comment by luizgrp** [comment]
I think the rtlMode param might still be useful when using an Icon that is not "AutoMirrored" or when calling Icon with a [drawable](https://github.com/google/horologist/blob/879118c2d83f1016261c2cdb0b70b8d4282ed007/compose-material/src/main/java/com/google/android/horologist/compose/material/Icon.kt#L66)?

If you agree then I think we should just update our code to not pass rtlMode when using AutoMirrored Icons, and maybe update the kdocs to:

```kotlin
/**
 * This component is an alternative to [Icon], providing the following:
 * - a convenient way of setting the icon to be mirrored in RTL mode;
 * 
 * Leave [rtlMode] set to [IconRtlMode.Default] when the Icon used is "auto mirrored", 
 * e.g. from the [Icons.AutoMirrored] set, or with `android:autoMirrored="true"` set in 
 * the XML vector file.
 */
```

**Comment by yschimke** [comment]
Maybe warn/fail if autoMirror is true? It's available in the api.

**Comment by luizgrp** [comment]
sounds good!

**Pull request closed without merging**
