### PR TITLE
Fix Card Padding

### PR DESCRIPTION
**Pull request by yschimke**
#### WHAT

Fix Card Padding and add tests.

#### WHY

Was showing incorrectly when onLongClick was missing.

#### Checklist :clipboard:
- [ ] Add explicit visibility modifier and explicit return types for public declarations
- [ ] Run spotless check
- [ ] Run tests
- [ ] Update metalava's signature text files

### CODE REVIEW

**Comment by yschimke** [comment]
Comparison with the bug

image

**Comment by yschimke** [comment]
cc @amankhoza

**Review by amankhoza — APPROVED** [review]
Change looks good to me, might not be worth fixing but worth noting screenshots look like the padding across buttons with and w/o longClick is still slightly inconsistent.

**Comment by yschimke** [comment]
@amankhoza I think that's the custom padding vs standard padding. If not, maybe attach a picture or video of the diff.

**Comment by amankhoza** [comment]
Ah yes you're right it is just the custom padding.

**Pull request merged**
